# Generated by Django 3.0.5 on 2020-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsAnswers',
            fields=[
                ('answer_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(auto_created=True)),
                ('correct', models.BinaryField()),
            ],
        ),
    ]
