# Generated by Django 3.0.5 on 2020-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200421_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsanswers',
            name='answer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
