# Generated by Django 3.0.5 on 2020-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200421_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsanswers',
            name='correct',
            field=models.BooleanField(),
        ),
    ]
